import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`antialiased p-6 overflow-hidden`}>
        <Providers>
          <div>
            {(session != null && session.user != undefined) ? <span>Logged in as <b>{session.user.name}</b></span> : <span>Currently not logged in. Use the <i>Sign In</i> button to login</span>}
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
